### PR TITLE
Help Pane for Trident DI

### PR DESCRIPTION
**Pull request by PennyZhou-MSFT**

### CODE REVIEW

**Comment by PennyZhou-MSFT** [comment]
#sign-off

**Review by ptyx507x — APPROVED** [review]

**Comment by ptyx507x** [comment]
#sign-off

**Comment by JasonWHowell** [comment]
@PennyZhou-MSFT  please use the private repo for all changes.

**Comment by JasonWHowell** [comment]
@PennyZhou-MSFT it's https://github.com/MicrosoftDocs/powerquery-docs-pr/ in this case.

**Pull request closed without merging**
