### PR TITLE
Unifying Resource Path Contents Into Single Page

### PR DESCRIPTION
**Pull request by bgribaudo**
Currently, both [Handling Resource Path](https://learn.microsoft.com/en-us/power-query/handling-resource-path) and [Handling Authentication](https://learn.microsoft.com/en-us/power-query/handling-authentication) talk in depth about resource paths.

With the exception of "Excluding Required Parameters from your Data Source Path", these two pages have approximately the same text describing resource paths, so largely duplicate each other.

This PR places a merge of the two page's contents on this topic into the resource path page and removes resource path content from the authentication page.

Thinking that 1 source for content on this topic is better than two.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@ptyx507x - Can you review this PR? The changes are so extensive that the content should be moved to the private repo for validation checks. Let us know if you need help doing this.

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ptyx507x** [comment]
@ShannonLeavitt we need an engineer to review these code changes. Could you please assign this to @mattmasson ?

**Comment by Court72** [comment]
#assign: @mattmasson

**Comment by JasonWHowell** [comment]
The conflicts are too hard to resolve. The changes would need to be repeated on a fresh copy of main branch. 
@bgribaudo we'll pull this branch internally and try to fix the branch in a piecemeal fashion to avoid the numerous conflicts. 
#assign:dougklopfenstein

Thanks!  Jason

**Comment by bgribaudo** [comment]
Thanks, @JasonWHowell. Anything I can do to help with this?

**Comment by JasonWHowell** [comment]
@bgribaudo we have quite a backlog of work right now, so sorry we're slow. 

If you have time though, this change has to be redone from scratch, since the conflicts are too difficult to pick apart. I'd close this PR and start fresh with a copy from the "main" branch. There were too many changes done before this one got merged, unfortunately. 

Thanks, Jason

**Comment by DougKlopfenstein** [comment]
A separate private pull request was created because of the numerous conflicts that have occurred over time in this pull request. The new pull request is listed above. That pull request has been merged into the documentation, so this private pull request is now redundant and is closed.

**Comment by bgribaudo** [comment]
Thank you, Doug!

**Pull request closed without merging**
