### PR TITLE
Update postgres.md

### PR DESCRIPTION
**Pull request by oseghr**
Line 34: Added installation section for Power Apps and how to download the exact installer for Postgresql connector with power apps.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@bezhan-msft - Could you review this PR?

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by DougKlopfenstein** [comment]
@oseghr 

Add a `#sign-off` comment to signal that the PR is ready to go through final review and then go live.

**Comment by Court72** [comment]
Hi @DougKlopfenstein - In the public repo, the assigned reviewer should add a `#sign-off` comment. If you'd like @oseghr to confirm that the PR is ready to merge first though, we can wait for confirmation. Thanks!

**Comment by Court72** [comment]
@DougKlopfenstein, @bezhan-msft, @oseghr 

Is this PR ready to merge?

**Comment by DougKlopfenstein** [comment]
#sign-off

**Pull request merged**
