### PR TITLE
4/11/2024 - Wolters Kluwer CCH Tagetik Power BI connector

### PR DESCRIPTION
**Pull request by FBattaglia999**
Documentation for Wolters Kluwer CCH Tagetik Power BI connector

### CODE REVIEW

**Comment by FBattaglia999** [comment]
@microsoft-github-policy-service agree [company="Wolters Kluwer"]

**Comment by FBattaglia999** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@FBattaglia999 - Thank you for your contribution. A member of the content team will review it.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by DougKlopfenstein** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@FBattaglia999 - this PR has been approved by the @DougKlopfenstein, but there are a couple issues that need to be resolved before we can merge. 

1. all the image file names must be lowercase, including the .png extensions. can you change them for the following files:

   - powerquery-docs/connectors/media/wolters-kluwer-cch-tagetik/authentication-credentials.PNG
   - powerquery-docs/connectors/media/wolters-kluwer-cch-tagetik/dashboard.PNG
   - powerquery-docs/connectors/media/wolters-kluwer-cch-tagetik/data-model.PNG

1. Alt text must be a full sentence with a period, and should describe what the image is. Eg. "Screenshot showing the Save dialog box with the Open button selected." 

After you make these changes. we can review again and merge. 

Thanks.

#hold-off

**Comment by DougKlopfenstein** [comment]
Hi @FBattaglia999 
I've updated the image alt-text in the connector article, but don't have the ability to change the names of the image files themselves. You'll need to update those. Once you have the image file names updated just type `#sign-off` in a comment and the editors will check again and merge your pull request.

**Comment by Jak-MS** [comment]
@FBattaglia999 @DougKlopfenstein - in case it's helpful, I've opened a new PR with the corrected file names (and all the other commits from this PR).  See https://github.com/MicrosoftDocs/powerquery-docs/pull/543 .  If that looks okay, @DougKlopfenstein , we can merge that and close this one. Thanks.

**Comment by DougKlopfenstein** [comment]
@Jak-MS  - looks good to me, please go ahead and do that. Thanks.

**Pull request closed without merging**
