### PR TITLE
Adding mention of OnTestConnector

### PR DESCRIPTION
**Pull request by bgribaudo**
Documenting how `Table.View`'s `OnTestConnector` handler works.

### CODE REVIEW

**Comment by Court72** [comment]
@ptyx507x

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ptyx507x** [comment]
@ShannonLeavitt we need an engineer to review these code changes. Could you please assign this to @mattmasson ?

**Comment by Court72** [comment]
#assign: @mattmasson

**Comment by bgribaudo** [comment]
Thanks, @mattmasson!

Do you suggest I close this, or leave it open pending the changes you mention?

**Comment by JasonWHowell** [comment]
@bgribaudo can you please help track the needed product enhancement, and we'll close the doc PR for now? 
I'm guessing Power BI ideas forum under Fabric, but not 100% sure if Matt's team monitors that forum. https://ideas.fabric.microsoft.com/?forum=2d80fd4a-16cb-4189-896b-e0dac5e08b41

**Pull request closed without merging**
