### PR TITLE
Add documentation for the LEAP connector

### PR DESCRIPTION
**Pull request by appintbot-leapdev**
- This PR adds documentation for the [LEAP](https://www.leaplegalsoftware.com) connector.
- As a custom connector (pre-certification), the LEAP connector has been successfully evaluated by ~25 law firms, representing ~800 users, in multiple countries over the past six (6) months.
- Pending Microsoft's capacity and approval, we hope to have the LEAP connector certified and released at Microsoft's earliest opportunity.

Thank you in advance.

### CODE REVIEW

**Comment by appintbot-leapdev** [comment]
@microsoft-github-policy-service agree [company="LEAP"]

**Comment by appintbot-leapdev** [comment]
@microsoft-github-policy-service agree company="LEAP"

**Comment by Court72** [comment]
@appintbot-leapdev - Thanks for your pull request. A member of the content team will review it.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by appintbot-leapdev** [comment]
Can we please have an update on this PR? Thank you in advance.

**Comment by appintbot-leapdev** [comment]
@DougKlopfenstein I understand that other connector documentation PRs are assigned to you. We previously worked with @bezhan-msft, who has recently departed (email address is now hard bouncing with no auto-response). Can you please assist us? Our target is the certified connector's inclusion in the Power BI Desktop February 2024 or March 2024 release. Thank you in advance.

**Pull request closed without merging**
