### PR TITLE
Planview Rebranding

### PR DESCRIPTION
**Pull request by jrsilva24**

### CODE REVIEW

**Comment by jrsilva24** [comment]
> 

@microsoft-github-policy-service agree [company="{Planview}"]

**Comment by cmcclister** [comment]
Hi @bezhan-msft please let me know if this PR is approved to merge. Thanks! cc @JasonWHowell

**Comment by bezhan-msft** [comment]
The icon and naming updates look fine from my side. 

This isn't released in PROD yet, right? This is ETA November?

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by DougKlopfenstein** [comment]
I've reviewed and approved the changes. Whenever the changes are ready to be merged, please enter "#sign-off" (without the quotes) as a comment. Once signed off, the changes will be merged. (For now, I'll assume that the sign-off will occur in November.)

**Comment by cmcclister** [comment]
#sign-off

**Comment by cmcclister** [comment]
Hi @bezhan-msft @DougKlopfenstein is there any way to merge this PR now that it has been approved? Thanks! cc @JasonWHowell

**Comment by JasonWHowell** [comment]
@cmcclister Are you asking because you don't see the merge button? 
There was a comment that this was timed to a release, so that needs to be checked on first.

@bezhan-msft what's the date this needs to go live? It is already shipped in the product?

Thanks, Jason

**Comment by DougKlopfenstein** [comment]
The October version of Power BI Desktop still uses the old designations. I'll check again when the November version of Power BI Desktop is released this month.

**Comment by JasonWHowell** [comment]
@cmcclister I'll add you. But please don't sign off without the author's say. These are time releases potentially, as per Doug's review.

**Comment by bezhan-msft** [comment]
#sign-off

**Comment by DougKlopfenstein** [comment]
#hold-off
Waiting to determine why all changes aren't in Power BI Desktop.

**Comment by DougKlopfenstein** [comment]
The November release of Power BI Desktop didn't contain all of the changes documented in this pull request. Therefore, a private pull request was made that contains the changes that were actually made in Power BI Desktop and Power Query Online, which is now live. When the final changes to this connector configuration is made in Power BI Desktop is make, another private pull request will be made to include those changes, and this public pull request will be closed.

**Review by cmcclister — APPROVED** [review]

**Comment by cmcclister** [comment]
@DougKlopfenstein @bezhan-msft I reviewed and approved this PR, but I have no option to merge it. Please advise on how I should proceed. Thanks!

**Comment by DougKlopfenstein** [comment]
This public pull request is being closed because all of the changes provided in this public pull request were copied into two private pull requests so that the November update to the Planview connector names could be merged. Then, when the last of the Planview connector names were integrated into Power BI Desktop in December, another private pull request (mentioned in the comments above) was created to finish up the name changes. Therefore, this public pull request is now redundant.

**Pull request closed without merging**
