### PR TITLE
Updated img alt text language

### PR DESCRIPTION
**Pull request by helloiamcait**
In the alt text for the first img:
- Capitalize "Query"
- Fix typo "through"
- Use clearer language
- Change alt text destination names to reflect destination names in image

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@ptyx507x - IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Our team should be able to resolve the merge conflict after you sign off.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ptyx507x** [comment]
#sign-off

**Comment by helloiamcait** [comment]
Conflicts have been resolved.

**Comment by Court72** [comment]
@bezhan-msft, @DougKlopfenstein 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by DougKlopfenstein** [comment]
#sign-off

**Comment by ptyx507x** [comment]
#sign-off

**Pull request merged**
