### PR TITLE
Intersystems Health Insight from Patch 1

### PR DESCRIPTION
**Pull request by jbolinsky**
Intersystems Health Insight connector

### CODE REVIEW

**Comment by Jak-MS** [comment]
@jbolinsky - i think you'll need to work with @DougKlopfenstein for this new article.

#assign: @DougKlopfenstein 

@DougKlopfenstein 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.

NOTE: new articles should be submitted through the private repo

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by jbolinsky** [comment]
@DougKlopfenstein  - Do you know when this request will be merged?

**Comment by DougKlopfenstein** [comment]
@jbolinsky - it will be merged once the connector shows up in at least one instance of Power Query (that is, in Power BI Desktop, Power BI service, etc.).

**Comment by DougKlopfenstein** [comment]
@jbolinsky - The article is ready to be merged, but you still need to add a table of contents entry for the connector. The table of contents file is toc.yml. You also need to add the connector to the list of connectors. The list is in alphabetical order and the file is connectors/index.md. Once these additions are made, this pull request can be merged.

**Comment by jbolinsky** [comment]
@DougKlopfenstein - I've submitted the requested changes

**Comment by DougKlopfenstein** [comment]
@jbolinsky  - In the index file, you need to change the name of the InterSystems Health Insight icon from InterSystemsHealthInsight64.png to intersystems-health-insight-64.png (along with changing the actual name of the .png file). Otherwise the name won't pass our editing process because it doesn't meet the Microsoft style rules.

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by DougKlopfenstein** [comment]
@jbolinsky - The changes have all been approved. Just add a `#sign-off` comment to this pull request and the pull request will be merged.

**Comment by jbolinsky** [comment]
#sign-off  - All changes approved, and signed off

**Comment by Court72** [comment]
@DougKlopfenstein 

These commits need to be pulled into the private repo for staging, validation, and Acrolinx and to get it merged. Let us know if you'd like the PR review team's help with moving the commits.

If you need it, the metadata/ownership info and the process for pulling content to the private repo are documented [here](https://review.docs.microsoft.com/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=main#pull-public-commits-to-the-private-repo-for-updates-staging-publication).

**Pull request merged**
