### PR TITLE
Get rid of Beta flag for SingleStore Power BI connector

### PR DESCRIPTION
**Pull request by okramarenko**
SingleStore PowerBI connector went GA in the latest Power BI release. This PR is to update the docs to correspond to this fact.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@DougKlopfenstein 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by DougKlopfenstein** [comment]
Hi @okramarenko 
Before this pull request can be merged, you also need to remove "(Beta)" from the SingleStore name in the Power Query table of contents. Once that is done, I can approve this pull request and it can be merged.

**Comment by okramarenko** [comment]
@microsoft-github-policy-service agree company="SingleStore"

**Comment by JasonWHowell** [comment]
Reopen the PR to get a clean file list diff

**Comment by DougKlopfenstein** [comment]
#sign-off

**Pull request merged**
