### PR TITLE
Add BuildingConnected documentation

### PR DESCRIPTION
**Pull request by joefields**
Add BuildingConnected & TradeTapp connector documentation. This is a new connector that is currently going through certification.

### CODE REVIEW

**Comment by Court72** [comment]
@joefields - Thanks for your pull request. A member of the content team will review it.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by DougKlopfenstein** [comment]
#sign-off

**Comment by DougKlopfenstein** [comment]
@joefields - The connector article has been approved. You need to add a `#sign-off` comment to this PR to move forward with merging this pull request.

**Comment by Court72** [comment]
Hi @DougKlopfenstein 

The commits need to be moved into the private repo for staging, validation, Acrolinx, and to get it merged.

If you need it, the metadata/ownership info and the process for pulling content to the private repo are documented [here](https://review.docs.microsoft.com/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=main#pull-public-commits-to-the-private-repo-for-updates-staging-publication).

**Comment by joefields** [comment]
#sign-off

**Pull request merged**
