### PR TITLE
Adds help documentation for Smartsheet EU

### PR DESCRIPTION
**Pull request by work-insights-data**
This adds help documentation for the Smartsheet EU connector.

### CODE REVIEW

**Comment by work-insights-data** [comment]
@microsoft-github-policy-service agree [company="Smartsheet"]

**Comment by work-insights-data** [comment]
@microsoft-github-policy-service agree company="Smartsheet"

**Comment by Court72** [comment]
@work-insights-data - Thanks for your pull request. A member of the content team will review it.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ptyx507x** [comment]
@work-insights-data please work through the certification process to enable a new connector entry if needed. We cannot process a PR until a connector is certified. We will close this PR, but you can submit a new one once the new connector is certified

**Comment by ptyx507x** [comment]
#please-close

**Pull request closed without merging**
