### PR TITLE
Changes for Apr 2023 re-certification of EQuIS connector

### PR DESCRIPTION
**Pull request by mathew-weaver**
Remove the "Beta" attribute and remove the row number limitation.

### CODE REVIEW

**Comment by mathew-weaver** [comment]
@Jak-MS Just to clarify, are you wanting me to review the PR and add the sign-off tag? Or are you asking @DougKlopfenstein to do that?

**Comment by Jak-MS** [comment]
@mathew-weaver - apologies for the confusion. typo... all PRs in the powerquery-docs repo should be reviewed by @bezhan-msft or @DougKlopfenstein .  I've edited my earlier comment.

**Comment by DougKlopfenstein** [comment]
Hi @mathew-weaver 
To remove all instances of the Beta tag (and its equivalents), you'll need to:
* Remove the (Beta) tag from the table of contents (toc.yml).
* Remove the (Beta) tag from the list of all connectors (connectors/index.md).
* Change the Release state in the Summary table from "Preview" to "Generally Available" (connectors/equis.md).

**Comment by mathew-weaver** [comment]
@DougKlopfenstein I pushed the changes requested in your last comment ([here](https://github.com/MicrosoftDocs/powerquery-docs/pull/396#issuecomment-1508921292)). I updated _ms.date_ within the _equis.md_ file, but not within _toc.md_ or _index.md_. Please let me know if I should update _ms.date_ in those files also.

**Comment by DougKlopfenstein** [comment]
All of the updates shown in this pull request have been done in the private pull request mentioned above. This private pull request was created to overcome the conflicts in this public pull request. Since all of the changes in this pull request were made in the private pull request, this PR is now redundant and is closed.

**Pull request closed without merging**
