### PR TITLE
Add Service principal support as auth. types

### PR DESCRIPTION
**Pull request by adityajain2408**
for the following connectors: ADLS gen1, Web, SP online, Azure SQL database, Dataverse

### CODE REVIEW

**Comment by American-Dipper** [comment]
@bezhan-msft - can you review the proposed changes?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by JasonWHowell** [comment]
Doug has emailed a question to the contributor for clarification. One connector may not support Service Principal.

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by adityajain2408** [comment]
#sign-off

**Comment by DougKlopfenstein** [comment]
#sign-off

**Pull request merged**
