### PR TITLE
Denodo updates 202204

### PR DESCRIPTION
**Pull request by denodo-research-labs**
This PR contains:

   * Explanation on the connection string validation method added to version 1.1 of the connector submission (29 March).
   * Some minor text fixes and style changes.

### CODE REVIEW

**Comment by JasonWHowell** [comment]
Fixing the merge conflict. The author tag doesn't support multiple values.

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[396549f](https://github.com/denodo-research-labs/powerquery-docs/commits/396549f35fc01bb1901c8088a1a75e9696af31d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerquery-docs/Connectors/Denodo.md](https://github.com/denodo-research-labs/powerquery-docs/blob/denodo-updates-202204/powerquery-docs/Connectors/Denodo.md) | :warning:Warning | | [Details](#user-content-b832052b6cf049194800bbe7c6f9edea-ef0866f1)
[powerquery-docs/Connectors/media/denodo/DataSourceSettingsSelectDenodo.PNG](https://github.com/denodo-research-labs/powerquery-docs/blob/denodo-updates-202204/powerquery-docs/Connectors/media/denodo/DataSourceSettingsSelectDenodo.PNG) | :white_check_mark:Succeeded | |

<a id="b832052b6cf049194800bbe7c6f9edea-ef0866f1"></a>
### [powerquery-docs/Connectors/Denodo.md](https://github.com/denodo-research-labs/powerquery-docs/blob/denodo-updates-202204/powerquery-docs/Connectors/Denodo.md)
 - **Line 58, Column 1**: **[Warning: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````
 - **Line 62, Column 1**: **[Warning: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0cb89e64-16a6-f377-e4a4-6c9012738630/202207211743251092-239/BuildReport?accessString=f518b374224914d476b176f3bbecc00b5081ec13f391b5650e1e568dec85412d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0cb89e64-16a6-f377-e4a4-6c9012738630?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[3898e59](https://github.com/denodo-research-labs/powerquery-docs/commits/3898e592558898d30c365860a053f113723aace5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerquery-docs/Connectors/Denodo.md](https://github.com/denodo-research-labs/powerquery-docs/blob/denodo-updates-202204/powerquery-docs/Connectors/Denodo.md) | :white_check_mark:Succeeded | |
[powerquery-docs/Connectors/media/denodo/DataSourceSettingsSelectDenodo.PNG](https://github.com/denodo-research-labs/powerquery-docs/blob/denodo-updates-202204/powerquery-docs/Connectors/media/denodo/DataSourceSettingsSelectDenodo.PNG) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0cb89e64-16a6-f377-e4a4-6c9012738630/202207211745363620-239/BuildReport?accessString=cc40e1ccffe4812f29e61eb71f8144c6ef62458d06f7c59d1cf07eaeba70ffaa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0cb89e64-16a6-f377-e4a4-6c9012738630?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JasonWHowell** [comment]
@dougklo this one looks good to me. Can you please confirm.

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[0975aa4](https://github.com/denodo-research-labs/powerquery-docs/commits/0975aa4516927e404c68921158ba1e372c2e8847)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerquery-docs/Connectors/Denodo.md](https://github.com/denodo-research-labs/powerquery-docs/blob/denodo-updates-202204/powerquery-docs/Connectors/Denodo.md) | :white_check_mark:Succeeded | |
[powerquery-docs/Connectors/media/denodo/DataSourceSettingsSelectDenodo.PNG](https://github.com/denodo-research-labs/powerquery-docs/blob/denodo-updates-202204/powerquery-docs/Connectors/media/denodo/DataSourceSettingsSelectDenodo.PNG) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0cb89e64-16a6-f377-e4a4-6c9012738630/202207211839312277-239/BuildReport?accessString=1ebdb0c408ec85dcf54025d105cee74401e144fe72015703363ee44975232215).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0cb89e64-16a6-f377-e4a4-6c9012738630?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by JasonWHowell** [comment]
Docs Build status updates of commit _[ee52a63](https://github.com/denodo-research-labs/powerquery-docs/commits/ee52a637feb635d5459481cacbf06013afefafac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerquery-docs/Connectors/Denodo.md](https://github.com/denodo-research-labs/powerquery-docs/blob/denodo-updates-202204/powerquery-docs/Connectors/Denodo.md) | :white_check_mark:Succeeded | |
[powerquery-docs/Connectors/media/denodo/DataSourceSettingsSelectDenodo.PNG](https://github.com/denodo-research-labs/powerquery-docs/blob/denodo-updates-202204/powerquery-docs/Connectors/media/denodo/DataSourceSettingsSelectDenodo.PNG) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0cb89e64-16a6-f377-e4a4-6c9012738630/202207261914107112-239/BuildReport?accessString=cf330bc7c27be5d8d9950eae6ce0e2c5b9190b3c837f8e5f1c905d0584840c92).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0cb89e64-16a6-f377-e4a4-6c9012738630?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
