### PR TITLE
Kyvosdevelopers kyvos odbc doc1

### PR DESCRIPTION
**Pull request by kyvosdevelopers**
Hi Team,

Please review the Kyvos ODBC connector document and update us if any other information is needed.

Thanks

### CODE REVIEW

**Comment by kyvosdevelopers** [comment]
@microsoft-github-policy-service agree [company="{Kyvos Insights}"]

**Comment by kyvosdevelopers** [comment]
@microsoft-github-policy-service agree company="Kyvos Insights"

**Comment by Court72** [comment]
@kyvosdevelopers, Thanks for your pull request. A member of the content team will review it.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by DougKlopfenstein** [comment]
Hi @kyvosdevelopers  - Just so that you're aware, blurring out personal or secret information in images is no longer sufficient to prevent hackers from gaining the information you've blurred out. AI is now capable of undoing blurring effects. So if you want to prevent this information from being general knowledge, replace the information with false info, such as "TestServer" or some other non-existent information. You will need to update your images before we can merge your content.

**Comment by kyvosdevelopers** [comment]
Hi @DougKlopfenstein thanks for your inputs, we are working on it and will update the images at earliest.

**Comment by kyvosdevelopers** [comment]
@DougKlopfenstein I have updated the images, please check and update me if any other changes are required.

**Comment by DougKlopfenstein** [comment]
@kyvosdevelopers - two of your images contain grayed out information. Modern AI is now capable of unblurring the image and retrieving the information that's been blurred. For security reasons, you should use fake information that's not blurred out in these images (okta.png and settings.png). In addition, make sure that you want the Kyvos Server information in directquery.png and load.png to be available to the public. If not, make up a fake Kyvos Server name and replace that information in both of those images.

In addition, the names of the image files should contain only lower-case letters and words should be separated by hyphens. For example, kyvos-odbc-64. png is correct. EditCredentials.png should be changed to edit-credentials.png. DirectQuery.png should be changed to directquery.png (since DirectQuery is one word). Also, OAuth2_0.png should be changed to oauth2-0.png (with a dash instead of an underscore. The dash character is the only other character allowed into filenames except numbers and lowercase letters.

**Comment by kyvosdevelopers** [comment]
Hi @DougKlopfenstein blurred images (okta.png and settings.png) are removed from folder as we are not using them. Updated images with smaller case and same updated in md file as well. All information in images is test server and it is fine.

Requesting you to please see and let me know if there are any other changes are required.

**Comment by DougKlopfenstein** [comment]
Hi @kyvosdevelopers - I've done a quick edit pass for Microsoft style. I don't see anything else that needs to be fixed. So, just add a `#sign-off` comment to this pull request. Once that's done, there will be a final review, which might require some changes or not.  Then the pull request will be merged.

**Pull request merged**
