### PR TITLE
Data Privacy Firewall: Wording Tweak + Typo Fix

### PR DESCRIPTION
**Pull request by bgribaudo**
* Proposing to change "randomly" -> "directly", as without the firewall, random access isn't occurring; rather, direct access is.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@ehrenMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by ehrenMSFT — APPROVED** [review]

**Comment by ehrenMSFT** [comment]
#sign-off

**Comment by Court72** [comment]
@DougKlopfenstein, @bezhan-msft 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Comment by Court72** [comment]
#hold-off until sign-off from Bob or Doug.

**Pull request merged**
