### PR TITLE
Update Oracle and Power Query instructions with new Oracle Client for MS Tools

### PR DESCRIPTION
**Pull request by alexkeh**
Includes instructions to use new Oracle Client for MS Tools that streamlines setting up ODP.NET for Power Query access to Oracle DB and Autonomous DB. Fixed validation issues found in initial PRs.

Updated screenshots to reflect new Power BI Desktop Azure AD connectivity option to Oracle DBs.

Updated some Oracle terminology.

### CODE REVIEW

**Comment by American-Dipper** [comment]
@bezhan-msft - can you review the proposed changes?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by JasonWHowell** [comment]
#assign:DougKlopfenstein

**Comment by alexkeh** [comment]
@bezhan-msft  and @DougKlopfenstein Do you have any feedback on these proposed doc changes to the Oracle Power Query setup instructions page? If everything looks fine, please sign off. Thanks!

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by DougKlopfenstein** [comment]
#sign-off

**Comment by Jak-MS** [comment]
<reviewed>

**Pull request merged**
