### PR TITLE
adds documentation for supermetrics connector

### PR DESCRIPTION
**Pull request by diegomotasuper**
Adding info for Supermetrics connector

### CODE REVIEW

**Comment by diegomotasuper** [comment]
@microsoft-github-policy-service agree company="Supermetrics"

**Comment by American-Dipper** [comment]
@TylerMSFT - can you review the proposed changes?  

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by American-Dipper** [comment]
notified content owner

**Comment by JasonWHowell** [comment]
#reassign:dougklo

**Comment by JasonWHowell** [comment]
#reassign:DougKlopfenstein

**Review by jacekpiatkowskism — APPROVED** [review]
lgtm 👍

**Review by cadamini — COMMENTED** [review]
Older pending review that removes blank lines and fixes the indentation for images in the procedure/numbered list.

**Comment by JasonWHowell** [comment]
#reassign:ptyx507x
#assign:jonburchel

**Pull request merged**
