### PR TITLE
Update web.md

### PR DESCRIPTION
**Pull request by veerendrajagatha**
We support Organizational authentication type in Service, which is OAuth2. Hence removed the below mentioned note. 

[

   >[!Note]
   >When uploading the report to the Power BI service, only the **anonymous**, **Windows** and **basic** authentication methods are available.

]

### CODE REVIEW

**Comment by Court72** [comment]
@bezhan-msft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by veerendrajagatha** [comment]
@Court72 @bezhan-msft is leaving msft today. Wondering if you can follow up with his backup?

**Review by ehrenMSFT — APPROVED** [review]

**Comment by Jak-MS** [comment]
@DougKlopfenstein - I fixed the merge conflict. @ehrenMSFT - approved earlier. If this looks good, can you sign-off?

**Comment by DougKlopfenstein** [comment]
#sign-off

**Pull request merged**
