### PR TITLE
Documentation for the new Zendesk Data connector

### PR DESCRIPTION
**Pull request by JinHuangAtZen**
Providing user documentation for the new Zendesk Data custom connector

### CODE REVIEW

**Comment by JinHuangAtZen** [comment]
> @JinHuangAtZen please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="Zendesk"]

**Comment by JinHuangAtZen** [comment]
> @JinHuangAtZen please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Zendesk"

**Comment by Court72** [comment]
@JinHuangAtZen - Thank you for your contribution. A member of the content team will review it.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by jonburchel** [comment]
@JinHuangAtZen can you also update index.md to add your logo and the relevant details for the connector index? You can copy one of the other examples there for the table structure and most of the contents except the logo and name. Otherwise I have the PR ready to merge once that's complete.

Thank you!

**Comment by JinHuangAtZen** [comment]
> @JinHuangAtZen can you also update index.md to add your logo and the relevant details for the connector index? You can copy one of the other examples there for the table structure and most of the contents except the logo and name. Otherwise I have the PR ready to merge once that's complete.
> 
> Thank you!

Hi @jonburchel , Thanks for the review, please see the updated PR with added logo and the updated index.md page.

**Comment by JasonWHowell** [comment]
#assign:ptyx507x
#assign:jonburchel

**Comment by JinHuangAtZen** [comment]
Hi @ptyx507x and @jonburchel just wondering is there anything else I need to do to get this PR approved?

**Comment by jonburchel** [comment]
This was merged as part of private PR https://github.com/MicrosoftDocs/powerquery-docs-pr/pull/1016

**Pull request closed without merging**
