### PR TITLE
Update Assemble Sign-in image for SSO

### PR DESCRIPTION
**Pull request by hofax**
- New sign-in image capture for SSO only

### CODE REVIEW

**Comment by bezhan-msft** [comment]
Hi @DougKlopfenstein can you please take a look at this at your convenience?

**Comment by bezhan-msft** [comment]
Hi @hofax - do you have a higher resolution picture available that you can update the PR with? It appears small in the docs.

**Comment by hofax** [comment]
@bezhan-msft Thanks for the heads up, I must have captured that image a little differently. I updated it with a higher resolution image.

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by bezhan-msft** [comment]
@hofax This is approved - due to merge conflicts I've gone ahead and made the change internally. You should see it live today at 6 PM Pacific (in 2.5 hours).

**Pull request closed without merging**
