### PR TITLE
Add documentation for the LEAP connector

### PR DESCRIPTION
**Pull request by appintbot-leapdev**
* Replaces original PR #493

### CODE REVIEW

**Comment by Jak-MS** [comment]
@DougKlopfenstein 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by appintbot-leapdev** [comment]
@DougKlopfenstein Miguel Escobar is our primary contact. This connector has been approved in the Connector Certification Portal and is presently in Deployment status. Thank you in advance.

**Comment by appintbot-leapdev** [comment]
@DougKlopfenstein Any update please? Thank you in advance.

**Comment by appintbot-leapdev** [comment]
@DougKlopfenstein Any update please? This certified connector is now available in the Power BI service, Data Factory, etc. Thank you in advance.

**Comment by DougKlopfenstein** [comment]
@appintbot-leapdev Connector documentation usually doesn't go live until all supported instances are available. Since the connector probably won't be available in Power BI Desktop until this month's update, the connector documentation will be published at that time.

**Review by jonburchel — APPROVED** [review]

**Pull request merged**
