### PR TITLE
Added inwink connector

### PR DESCRIPTION
**Pull request by paservois**

### CODE REVIEW

**Comment by paservois** [comment]
> 

@microsoft-github-policy-service agree company="inwink"

**Comment by Court72** [comment]
@paservois

Thanks for your contribution. A member of the content team will review it.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by JasonWHowell** [comment]
@paservois Are you working with anyone in Microsoft to certify the inWink provider?

**Comment by paservois** [comment]
> @paservois Are you working with anyone in Microsoft to certify the inWink provider?

@JasonWHowell I'm working with Bob Zhang

**Comment by DougKlopfenstein** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
Hi @DougKlopfenstein 

This content needs to be moved to the private repo to take advantage of automated checks. Let us know if you need help moving the content. Either here or in the private repo, you'll need to resolve these blocking issues before you sign off again:

**Following are blocking issues that need to be resolved before we can merge:**

powerquery-docs/connectors/inwink.md
* Lines 10-12: An introductory paragraph must appear between the H1 and the first H2.
* Run a spell check on this file. I happened to spot this typo: "authentiction" but there might be others.

powerquery-docs/connectors/media/inwink/auth1.png
powerquery-docs/connectors/media/inwink/auth2.png
* In this file name, insert a hyphen between "auth" and the number. The file name should describe the image, so if you can replace the current file names with more descriptive names, that would be ideal.

powerquery-docs/connectors/media/inwink/nav-data.png
* In this file name, spell out "nav".

powerquery-docs/connectors/media/index/inwink-64.png
powerquery-docs/connectors/media/inwink/auth2.png
powerquery-docs/connectors/media/inwink/auth1.png
* The use of the third-party logo and screenshots requires CELA review. If you've already had a CELA review, let us know in your next sign-off comment. Otherwise, remove the image until after you've had a CELA review.

	
***
	
**References**
	
[Pull request quality criteria](https://review.learn.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=main)
* (Blocking) [Content:](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=main#completecontent) The article must contain an introductory paragraph immediately below the H1 and a body of content with sufficient, complete content to stand on its own as an article. It shouldn't be a small fragment of information.
* (Blocking) New files and folders must follow the [File name and path guidelines](https://review.learn.microsoft.com/en-us/help/contribute/file-path-guidelines).
* (Blocking) New images that might be legally sensitive must be reviewed by the contributor's [CELA contact](https://fyc-prod.azurewebsites.net/). For more information, see the Learn platform [legal guidelines](https://review.learn.microsoft.com/en-us/help/contribute/contribute-legal-guidelines).

***
	
After you resolve the blocking issues, sign off again to start another review.
	
If you have questions about this review, send email to techdocprs@microsoft.com. Someone on the PR Review Team will help you.
	
Thanks

#hold-off

**Comment by JasonWHowell** [comment]
@ShannonLeavitt we handle connector articles with 3rd parties in the public repository so we can collaborate. No need to triage these right now. They will be handled in due time. Some take a few months of reviews to finalize.

**Comment by JasonWHowell** [comment]
@shannonleavitt oops I missed the Sign-off. @DougKlopfenstein  do you have a copy in the private repo to see the build preview?

**Comment by JasonWHowell** [comment]
Checking internally at https://github.com/MicrosoftDocs/powerquery-docs-pr/pull/960

**Pull request merged**
