### PR TITLE
Updated documentation for Autodesk Construction Cloud Connector

### PR DESCRIPTION
**Pull request by joefields**
Revised documentation for changes to Connector navigation in May 2023 Power BI release

### CODE REVIEW

**Comment by Jak-MS** [comment]
@bezhan-msft 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by bezhan-msft** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@joefields - thanks for updating the images. Can you resubmit the screenshots without the blurring? You can mask or partially mask (with the background color , "erasing" it ) personal information or replace it with fictitious data if you prefer. 

When you've completed this, tag @bezhan-msft for another review and sign off. thanks 

#hold-off

**Comment by joefields** [comment]
> @joefields - thanks for updating the images. Can you resubmit the screenshots without the blurring? You can mask or partially mask (with the background color , "erasing" it ) personal information or replace it with fictitious data if you prefer.
> 
> When you've completed this, tag @bezhan-msft for another review and sign off. thanks
> 
> #hold-off

@bezhan-msft, I have uploaded revised images with white out instead of the blurring for your review. Thanks!

**Comment by DougKlopfenstein** [comment]
Hi @joefields 
You'll also need to remove the "(Beta)" from Autodesk Construction Cloud entries in both the index.md file and the toc.yml file to complete this pull request.

**Comment by joefields** [comment]
> Hi @joefields You'll also need to remove the "(Beta)" from Autodesk Construction Cloud entries in both the index.md file and the toc.yml file to complete this pull request.

Hi @DougKlopfenstein, I have removed the beta flag from our connector in these two files and it is ready for your review.

**Review by DougKlopfenstein — APPROVED** [review]

**Comment by DougKlopfenstein** [comment]
#sign-off

**Pull request merged**
