### PR TITLE
Adding Falcon Connector

### PR DESCRIPTION
**Pull request by AntonioLandaluce**
Adding Falcon connector.

### CODE REVIEW

**Comment by Court72** [comment]
@AntonioLandaluce - Thank you for your contribution. Would you take a moment to sign the [Contributor License Agreement (CLA)](https://github.com/MicrosoftDocs/powerquery-docs/pull/488#issuecomment-1853466136)? After the CLA is signed, someone can review your pull request. Thanks!

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
hi @AntonioLandaluce - if you follow the instructions here:  https://github.com/MicrosoftDocs/powerquery-docs/pull/488#issuecomment-1854221965 , then we can move forward with this PR. thanks.

**Comment by AntonioLandaluce** [comment]
Hi, this PR is no longer necessary because another client will do it by himself. Many thanks! 

If I need to take any further action, please let me know :)

**Pull request closed without merging**
